jojoldu/junior-recruit-scheduler

README.md
더파머스(마켓컬리) 인턴 채용이 마감된듯하여 풀리퀘스트 보냅니다.
=> 더파머스(마켓컬리) 인턴 채용 마감

README.md
로엔 엔터테인먼트(카카오) 신입 공채-지원 기간 만료 삭제
=> 로엔 엔터테인먼트(카카오) 신입 공채-지원 기간 만료 삭제

README.md
컴투스 채용 기간이 만료되어 삭제하였습니다.
데브시스터즈의 경우 웹디자이너 신입 공고가 마감되어서 삭제하였고, 다른 채용 리스트를 추가했습니다.
=> 컴투스 채용 삭제 및 데브시스터즈 채용 추가

README.md
스마일게이트 서버개발캠프2018 모집이 시작되어 추가했습니다~
어디로 넣어야할지 고민했는데 전에 우아한테크캠프가 채용정보에 있었던거같아 채용정보에 넣었습니다.
=> 스마일게이트 서버개발캠프 모집 추가

README.md
이베이 신입 채용공고(~11/05)
플리토 주니어 백엔드 채용공고(~10/31)
네이버 핵데이 모집(~11/05)
삭제했습니다. 확인부탁드립니다.
=> 기한이 종료된 공고 삭제

README.md
네이버 체험형 인턴
1. 오디오플랫폼
2. 동영상 추천
3. 라이브서비스개발
=> 네이버 체험형 인턴 추가

README.md
오늘(11월 18일)까지인 NAVER 체험형 인턴십 모집 공고 삭제했습니다.
=> 기한이 오늘까지인 공고 삭제

README.md
2017 찾아라 프로그래밍 마에스터 (중소/중견기업 채용 연계 프로그래밍 대회)가 금일 오후 1시 30분까지로 연기되었지만 이제 접수 마감되어 삭제합니다.
=> 금일까지 접수 연기되었던 프로그래밍 대회 기한 마감되어 삭제

README.md
리디 데이터 엔지니어 채용공고에
자격 요건
핵심 직무 역량
- 백엔드 또는 데이터 엔지니어링 개발 경력 5년 이상
이 추가되었습니다.
신입채용이 사라진 것으로 보입니다.
=> 리디 데이터 엔지니어 신입/경력 -> 경력으로 변경.

README.md
정식 채용공고가 올라와 페이스북 링크를 대체하려고 합니다.
=> 라인플러스 채용공고 업데이트

README.md
3월 9일부터 3월 25일까지 서류접수가 가능한 네이버 AI 해커톤 2018 목록을 추가하였습니다 :)
=> [Add] 네이버 AI 해커톤 2018 목록을 추가한다

README.md
노리 웹 서버 개발자(신입)가 커리큘럼의 링크로 설정되어 있어서 찾아 가기 쉽게 원티드 채용 링크로 수정했습니다.
=> 노리 신입 개발자 링크 수정

README.md
우아한 테크캠프와 카카오 게임즈 채용 공고가 끝나서 삭제했습니다.
=> 종료된 채용 공고 삭제

README.md
기존 카카오/다음은 상시 채용으로 되어 있어서 상단에 별도로 추가 했습니다.
=> 카카오 블라인드 채용 추가

README.md
2017 카카오 코드 페스티벌 예선전, 본선 해설을 추가했습니다.
그리고 카카오 코딩 테스트 해설 링크가 계속 추가되면 너무 길어질 것 같아서 정렬을 수정해봤습니다. :)
감사합니다.
=> 2017 카카오 코드 페스티벌 해설 추가 및 링크 정렬 수정

README.md
카카오 기술블로그에 2차 오프라인테스트 해설이 게시됨에 따라 링크 추가하였습니다
=> 카카오 블라인드 공채 2차 테스트 해설 추가

README.md, db.json
라인 웍스 모바일 채용전제형 인턴 공고 추가하였습니다.
다행히도 [잡플래닛 평점](https://www.jobplanet.co.kr/companies/312497/reviews/%EC%9B%8D%EC%8A%A4%EB%AA%A8%EB%B0%94%EC%9D%BC)이 3.5네요 ^^;
다만 채용 공고가 js호출로 표시되는 방식이라 링크를 가져올 수가 없어서 전체 채용공고 링크로 대체하였습니다.
=> 라인 웍스 모바일 채용전제형 인턴 공고 추가

README.md
존재하지 않는 링크를 제거하고, 유효한 링크로 연결했습니다.
기존에 연결되어 있던 기여 가이드 파일이 삭제된 듯 하여, 기여자 그래프 페이지로 변경했습니다.
=> Fix broken link to contributors page

README.md, db.json
네이버 핵데이 행사의 접수기간 만료된 것으로 보여서 삭제했어요.
=> 네이버 핵데이 행사의 접수기간 만료

README.md, db.json
안녕하세요. 피플펀드에서 일하고 있는 한섬기입니다. 
저희 회사가 좋은 문구로 소개되어 있어서 사내에서 링크를 돌려보며 상당히 자랑스러워하고 있었는데, 오랜만에 들어와보니 사라져 있어서 깜짝 놀랐습니다. 저희는 상시 채용을 하고 있거든요.
기존 링크는 프론트엔드 개발자 채용으로 올라와 있었는데, 프론트엔드 개발자 채용은 필요시에만 올리고 있어서 항상 오픈되어 있는 백엔드 개발자 채용 공고로 수정하여 다시 추가요청 드립니다. 
기존 제목에 2~10년차만 있었으나, 연차와 무관하게 채용하고 있어 해당 문구는 삭제했습니다. (사실 근래에 신입으로 들어오신 분들이 몇몇 분 계십니다.)
=> 피플펀드 공고 재추가 요청드립니다.

README.md
잡코리아에 올라간 아이스크림 에듀 채용 공고가 마감되었습니다.
http://www.jobkorea.co.kr/Recruit/GI_Read/27910619?fbclid=IwAR2rGXythxuzQK8wQrPuPVJCqBbDMvA5viCNaFApPXXYqDEb2wqmVFVfHmQ
=> 아이스크림 에듀 채용 마감

README-en_EN.md, README-zh_CN.md, README.md, db.json
쿠팡 상반기 신입 공채 공고 링크가 존재하지 않아 해당 공고를 제거합니다.
=> 접수 마감된 모집 공고 제거

README.md
오늘 마감된 nc 인턴십  공고를 삭제하고, 
오늘 나온 네이버 예약 플랫폼 프론트엔드/백엔드 개발 인턴십(채용연계형)을 추가했습니다.
=> 마감된 채용공고 수정, 네이버 예약 플랫폼 인턴 추가 요청

README.md, db.json
안녕하세요.
네이버 공고를 자세히 살펴보니 체험형 인턴 이외에도,
리서치분야를 포함한 채용연계형 인턴도 있더라구요.
그래서 좀 더 구체적으로 유형과 채용연계형 인턴을 추가해봤습니다.
또한 db.json에 일정 시간에 오타가 있는 것 같아서 그 부분도 수정하였습니다. 
풀 리퀘스트가 아직 미흡하여서 검토 잘 부탁드립니다.
감사합니다.
=> 네이버 인턴 추가 및 유형 수정

README.md, db.json
안녕하세요
"네이버 동영상 플랫폼 (인턴)" 공고의 링크가 끊겻고,
네이버 커리어에서도 찾을 수 없어서 마감으로 판단하여 삭제했습니다.
=> 마감된 네이버 동영상 플랫폼 (인턴) 공고 삭제

db.json
링크 클릭할 경우, "찾을 수 없는 페이지 입니다." 로 이동하며, 온라인 테스트는 상시이나 체크인 미팅 일정은 마감된 것으로 보여 삭제했습니다 :)
=> 42 SEOUL 모집 마감

README.md
SI 직링크가 아닐 뿐더러 다른 정보들과 동등한 정도의 양질의 정보라고 생각할 수 없기 때문에 삭제를 제안합니다.
=> 나무위키 SI 문서 링크 삭제

README.md, db.json
- 프론트엔드 개발자 경력만 포함하도록 변경하였습니다.
- 각 파트별 링크가 private 링크라 권한이 없다고 나와서 public 링크로 변경하였습니다.
- 하단 추천 도서 요약정리 링크가 이제는 존재하지 않아 지웠습니다. 작성자 분 계정 자체가 없어진거 같습니다. https://www.slideshare.net/ddayinhwang9
=> 인프런 채용링크 수정

README.md
HitCount 이미지가 정상적으로 보이지 않아서 수정했는데, 사용해보지 않던 거라 간단하게 찾아보고 수정해서 적절한 수정인지 확신은 없네요.
다만 공식 페이지에서 알려주고 있는 방법이라 수정해봤어요.
=> HitCount가 정상적으로 보이지 않는 문제 수정

README.md, data/db.json
그린랩스 채용공고 클릭 시 "찾을 수 없는 페이지" 발생으로 삭제합니다.
=> 그린랩스 채용공고 삭제 

README.md, data/db.json
네이버파이낸셜 2022 상반기 대졸 신입 공채 공고가 올라와서 PR을 올립니다.
Backend, Frontend, STA/RA 분석 3개 직군에서 모집합니다.
=> 네이버파이낸셜 2022 상반기 대졸 신입 공채

README.md, data/db.json
2022 토스 NEXT 개발자 챌린지 공고를 추가하였습니다.
지원 대상자는 경력 3년 이하의 주니어 개발자입니다.
=> 2022 토스 NEXT 개발자 챌린지 추가
