jojoldu/junior-recruit-scheduler

README.md
서류 마감이 일요일까지로 늘어났습니다.
https://recruit.woowahan.com/#/techcamp 를 참조해주세요!
=> 우아한 형제들 서류 마감 수정

README.md
=> 라인 하계 개발 인턴 제거

README.md
SK 주식회사 C&C Code Genius 2017 코딩 테스트 추가 pr 입니다.
자세한 내용은 링크 참조해주세요!
https://programmers.co.kr/competitions/24/sk-%EC%A3%BC%EC%8B%9D%ED%9A%8C%EC%82%AC-cc-code-genius-2017
=> SK 주식회사 C&C Code Genius 2017 코딩 테스트 추가

README.md
면접 준비 할 때에 읽어 보면 좋을만한 기사, 블로그 글을 면접 팁에 추가했습니다. 
위치가 애매하긴 하지만, 기술 면접 관련 내용이라 면접팁에 추가 했습니다. 
내용이 카테고리에 안맞는다면, 위치 조정 말씀 해주시면 변경 하겠습니다.
=> [면접팁 추가] 기사, 블로그 상의 면접 관련 링크 추가

README.md
=> K-HACKATHON

README.md
NEXON COMPANY에서 2017 하계 신입 게임프로그래머를 모집하고 있어 추가했습니다.
=> 넥슨 컴퍼니 하계 신입 게임프로그래머 모집 추가

README.md
항상 눈팅만 하다가 좋은 채용정보가 있어서 추가했습니다 :)
=> 스켈터랩스 인턴 채용 추가

README.md
늘 감사히 보고 있다가, 좋은 글이 있어 PR 보내봅니다...!
=> 개발자를 채용하면서 느꼈던 것들 추가

README.md
=> 2017 글로벌 창업아이디어 해커톤 추가

README.md
격려 차 Special Thanks에 추가 부탁드립니다!
=> 송파구, AskDjango 해커톤 추가

README.md
=> 프론트엔드 관련 면접 후기 추가

README.md
=> 카카오 코드 페스티벌 입니다~!

README.md
[05.29 ~ 06.14] [2017 글로벌 창업아이디어 해커톤]
=> 2017 글로벌 창업아이디어 해커톤 접수기간 만료 삭제

README.md
SK 주식회사 C&C “Code Genius 2017” 접수기간 만료 삭제
=> SK 주식회사 C&C “Code Genius 2017” 접수기간 만료 삭제

README.md
채용 완료된 정보 - 줌인터넷, 카카오 내비
목적에 맞지 않은 정보 - 카카오톡 안티 어뷰징 경력 모집
잘못된 정보 - 다음 앱 iOS만 모집
=> 채용 완료 및 목적에 맞지 않은 정보 삭제, 잘못된 정보 수정

README.md
Add programming contest 2018 KAKAO 1ST BLIND RECRUITMENT
=> Add 2018 KAKAO 1ST BLIND RECRUITMENT

README.md
스마일게이트 신입 공채 추가건입니다.
마감일 종료 시각은 적혀있지 않아 기록하지 못했습니다.
확인 부탁드리겠습니다!
=> 스마일게이트 신입 공채 추가

README.md
캐시슬라이드 개발사인 NBT에서 신입 개발자 채용정보가 있어 추가했습니다. :)
=> NBT 신입 개발자 채용정보 추가

README.md
=> 넥슨 기술운영 시스템 개발 채용정보 추가

README.md
패치를 안하고 풀리퀘를 보냈네요. conflict 난건 수정했어요~ ;(
=> 넷마블 신입 공채 일정 추가

README.md
데브시스터즈의 채용을 확인해봤는데 채용 마감으로 나와서 풀 리퀘스트 보냅니다.
=> 데브시스터즈의 채용 마감

README.md
넥슨 신입 공채가 오픈되어서 PR 드립니다.
직군별로 페이지가 나누어져 있어서 따로따로 링크 했는데, 수정이 필요한 경우 다시 올리겠습니다!
=> 넥슨 신입 공채 정보 추가

README.md
=> 카카오 신입 개발자 공채 삭제

README.md
카카오의 채용은 지원 마감된 것 확인했고 넥슨의 채용은 들어갔을 때 아무 내용도 안나오고 검색을 해도 안나오는데 확인을 한 번 해보시는 것이 좋을 것 같습니다.
=> 지원 접수가 마감된 것으로 보이는 내용 삭제

README.md
9월 25일부터 시작되는 NC소프트 신입공채건 추가입니다.
확인 부탁드리겠습니다!
=> NC소프트 신입공채 추가

README.md
=> 스마일게이트 신입 공채 기간 만료 삭제

README.md
마이다스아이티 채용 마감으로 채용 카테고리에서 해당 항목을 삭제합니다.
=> 마이다스아이티 채용 마감으로 인한 항목 삭제

README.md
패션 A.I. 서비스를 만들고 있는 옴니어스에서 주니어 서버 개발자를 채용중입니다.
많은 관심 부탁드려요 :)
=> 옴니어스 주니어 서버 개발자 채용 추가

README.md
안녕하세요,
LaTeX 기반의 영문 이력서 템플릿 AwesomeCV와 이를 기반으로 만든 예제 이력서를 만들어 GitHub에 공개중입니다.
해당 가이드에 추가하면, 영문 이력서를 작성하시는 분들께 도움이 되지 않을까 하여 추가 해보았습니다.
본 가이드의 취지와 맞을지 검토 부탁드려요 :)
=> 영문 이력서 관련 팁 추가

README.md
=> 게임빌 / 컴투스 공채, NHN고도 상시채용 추가

README.md
자바 외에도 다양한 정보가 있어서 도움 될거 같아 이렇게 올려봅니다.
https://www.javatpoint.com/corejava-interview-questions
=> 제가 면접 준비 혹은 개인 공부할 때 참고 했던 사이트입니다. 

README.md
=> 넷마블 신입 공채 기간 마감 삭제

README.md
=> NC소프트 신입 공채 삭제

README.md
티몬 신입 공채 삭제 요청합니다~! 마감되는 채용이 많네요!
=> 티몬 신입 공채 삭제

README.md
=> 마감된 채용 공고 삭제

README.md
이스트소프트 & 줌인터넷 공채 기간 만료 삭제 요청드립니다!
=> 이스트소프트 & 줌인터넷 공채 기간 만료 삭제

README.md
@jojoldu 
#24 병역특례 옵션을 추가했습니다.
리뷰 부탁드립니다.
=> 병역특례 관련 옵션 추가

README.md
채용글을 수정하였더니 링크가 변경되었었네요!
아직 옴니어스의 채용이 끝나지 않았습니다.
많은 관심 부탁드립니다.😊😊
=> Add Omnious for start-up recruit

README.md
게임빌 / 컴투스 신입 공채 기간 만료 삭제 요청드립니다!
=> 게임빌 / 컴투스 신입 공채 기간 만료 삭제

README.md
라인 채용 연계형 동계 인턴 기간 만료 삭제 요청드립니다!
=> 라인 채용 연계형 동계 인턴 기간 만료 삭제

README.md
안랩 동계 인턴이 생겨서 추가합니다.
잡플레닛 평점 3.5점이네요.
=> 안랩 동계인턴 추가

README.md
=> 스마일게이트 서버개발캠프 기간 만료 삭제

README.md
programmers에서 진행하는 중소/중견기업 채용 연계 프로그래밍 대회 링크를 추가해도 될까요?
=> Add 중소/중견기업 채용 연계 프로그래밍 대회

README.md
면접 준비로 링크를 확인하던 중 작동하지 않는 링크가 있어서 삭제 요청드립니다.
=> 작동하지 않는 링크 삭제 요청합니다.

README.md
2017 찾아라 프로그래밍 마에스터의 마감 시간이 적혀있지 않아 추가합니다.
=> 2017 찾아라 프로그래밍 마에스터의 마감 시간 추가

README.md
=> 안랩 동계 인턴 삭제

README.md
NTS 동계인턴 추가합니다.
잡플레넷 평점 3.6점이고 SW개발, SW테스트 엔지니어, UI개발 모집하네요.
=> NTS 동계 인턴 추가 (잡플레넷 평점 3.6)

README.md
NTS 동계 인턴의 SW 개발부문이 기한 마감되어 삭제합니다.
=> 기한 마감된 동계 인턴

README.md
=> 마감 기한이 지난 인턴 삭제

README.md
아이디인큐 신입 웹 개발자 채용 지원이 마감되어 삭제합니다.
=> 아이디인큐 지원 마감 삭제

README.md
안녕하세요? 8퍼센트 개발팀을 맡고 있는 이호성입니다. 먼저 저희 회사를 추천 해 주셔서 감사합니다!
제가 최근에 쓴 글 중 신입 개발자 분들이 참고하실 수 있는 참고 자료를 2개 추가 하였습니다.
=> 8퍼센트 참고 자료 추가

README.md
=> 어라운드어스 채용마감되어 삭제.

README.md
=> 마감기한이 지난 채용 삭제

README.md
[LINE PLUS] App. Prototype 개발 인턴
공고 올라와서 추가했습니다~
=> 라인플러스 개발인턴 채용 추가

README.md
카카오/다음에서 종료된 채용공고가 있어 삭제했습니다~!
=> 종료된 채용공고 삭제했습니다~

README.md
- <https://github.com/NAVER-CAMPUS-HACKDAY/common>
=> Update Naver Campus Hack Day 2018 Summer

README.md
마감된 것으로 보이는 공고들을 삭제했어요.
확인을 해보시겠지만 큐브리드의 경우에는 제목에 `-> 마감`이 포함되어 있어 마감된 것으로 생각했어요.
=> 마감된 채용공고 삭제

README.md
- <https://github.com/tmoncorp/internship-2018>
=> 2018 티몬 하계 인턴십 프로그램

README.md
=> 프로그래머스 2018 Summer Coding 여름방학 스타트업 인턴 프로그램 추가입니다.

README.md
LINE PLUS 앱 프로토타입 개발인턴 및 네이버 핵데이 2018 섬머 삭제했습니다.
=> 마감된 채용및 해커톤 삭제

README.md
=>  마이다스 아이티 소프트웨어 개발 경진대회 추가

README.md
유데미 유료 강의 자료입니다. 강의 홍보는 아니고 도움이 돼서 공유하고자 올렸는데 유료 강의라는 것이 조금 마음에 걸리네요. 풀리퀘스트 안 받아주셔도 괜찮습니다.
=> 코딩 인터뷰 완벽 준비 추가

README.md
=> 블루홀, 라인플러스, 이베이코리아 하계인턴 추가

README.md
- 2018 SummerCoding - 여름방학 스타트업 인턴 프로그램 접수 마감으로 공고 삭제
=> 마감된 채용 행사 삭제

README.md
안녕하세요?
줌인터넷 포털 개발 신입공채가 나서 PR날립니다.
이유는 잡플래닛 평점 3.4점으로 신입이 성장하기에 최적의 환경이라 생각하기 때문입니다.
감사합니다.
=> 줌인터넷 채용 공고 추가

README.md
주니어 개발자를 위한 이력서 & 포트폴리오 작성법 및 면접 잘 보는 법에 대한 블로그를 올렸습니다.
저와 같은 주니어 개발자들에게 내용을 공유하고 싶습니다!
확인해주시고 pull request 받아주시면 감사하겠습니다 :)
항상 양질의 정보를 많이 제공해주셔서 감사합니다.
=> 이력서 & 포트폴리오 작성법에 대한 글 추가

README.md
김대희님 면접자료 repo 주소가 변경되어 PR 올립니다.
(얼마전에 아이디를 변경하신 것 같아요)
=> 김대희님 repo 주소가 변경되어 수정

README.md
2018년도 스마일게이트 하계 직무체험 인턴십 공고 추가입니다.
=> [추가] 2018년도 스마일게이트 하계 인턴십

README.md
이규원님이 CTO로 계신 오마이랩 프론트엔드 프로그래머 신입/경력 채용 공고 추가하였습니다 :)
=> 오마이랩 채용 공고 추가

README.md
채용기간 지난 공고 삭제하였습니다.
- [04.30 ~ 05.20] [2018 eBay Korea]
- [05.07 ~ 05.20] [줌인터넷 포털서비스 개발]
=> 채용기간 지난 공고 삭제 | 2018 eBay Korea Summer Internship, 줌인터넷 포털서비스 개발

README.md
종료된 채용 공고를 삭제했습니다.
1. 2018 컴투스 썸머 인턴십
2. 노리 웹 서버 개발자(신입)
=> 종료된 채용 공고 삭제

README.md
찾을 수 없는 페이지로 연결되서 해당 회사의 채용공고 페이지로 연결되도록 수정했습니다.
=> 찾을 수 없는 페이지로 연결된 URL을 채용공고 페이지의 URL로 수정

README.md
JBee(한재엽)님의 기술면접 자료 Repository에서 잘못되어있는 링크 URL을 수정했습니다
=> 잘못되어있는 URL 변경

README.md, db.json
제가 일하고 있는 인코어드 프런트엔드 개발자 채용공고 추가했습니다.
아래 세가지 조건을 만족하고 있고
> 유의미한 트래픽이 발생하고,
> 코드리뷰, 배포 자동화 등이 구축되어 있고,
> 코드 품질에 관심이 있는 회사를 얘기합니다.
[잡플래닛 리뷰](https://www.jobplanet.co.kr/companies/57935/reviews/%EC%9D%B8%EC%BD%94%EC%96%B4%EB%93%9C%ED%85%8C%ED%81%AC%EB%86%80%EB%A1%9C%EC%A7%80%EC%8A%A4)는 겨우 3.3점 턱걸이이지만
'내가 인코어드에서 일하는 이유'에 썼듯 더 나은 팀을 만들기 위해 
계속해서 노력하고 있습니다. 감사합니다.
=> 인코어드/에너톡 채용 추가

README.md
줌인터넷 공채(~07.29)
NHN 엔터테이먼트 인턴(채용시까지) 추가했습니다.
=> 줌인터넷신입채용, NHN Ent 인턴채용 추가

README.md
=> 페이지를 찾을 수 없는 글 삭제

README.md
=> 기간만료로 인한 삭제

README.md, db.json
=> 채용 마감시간 추가

README.md
페이지를 찾을 수 없어서 채용된 것으로 생각되 삭제했어요.
=> 페이지를 찾을 수 없는 공고 삭제

README.md
2018 카카오 코드 페스티벌 예선전, 본선 해설이 업데이트 되었습니다. :)
=> 2018 카카오 코드 페스티벌 예선전, 본선 해설 추가

README.md
=> 2019 카카오 신입 공채 1차 코딩 테스트 문제 해설 추가

README.md, db.json
마이뮤직테이스트 프론트엔드 신입/주니어 개발자 채용 PR 드립니다.
현재 잡플래닛 평점은 4.0 입니다.
https://www.jobplanet.co.kr/companies/56389/reviews/%EB%A7%88%EC%9D%B4%EB%AE%A4%EC%A7%81%ED%85%8C%EC%9D%B4%EC%8A%A4%ED%8A%B8
감사합니다.
=> 마이뮤직테이스트 개발자 채용

README.md
안녕하세요
제가 면접을 보면서 추려낸 공통 질문들입니다.
기억이 나는대로 질문들이 추가될 예정입니다.
=> 면접 예상 질문 추가

README.md
=> 카카오 블라인드 코딩테스트 연도 오타 수정

README.md
[Do-Hee(권희정, 박도연님)의 기술면접 자료 Repository](https://github.com/Do-Hee/tech-interview) 추가합니다. :)
=> 기술면접 자료 추가

README.md
=> 변경 된 주소 적용

README.md, db.json
매번 감사히 받아 보다가 첫 풀리퀘입니다.
혹시 잘못된 부분이나 수정사항 있으면 코멘트 부탁드립니다.
=> 겨울 스타트업 인턴 프로그램 공고 안내

README.md, db.json
이번에 NAVER CAMPUS HACKDAY가 열리네요~!
=> NAVER CAMPUS HACKDAY 추가

README.md, db.json
=> 파수닷컴 공채 종료

README.md
=> 2018 Winter Coding(겨울 스타트업 인턴 프로그램) 접수 마감으로 제거

README.md, db.json
NAVER CAMPUS HACKDAY 일정이 끝나서 삭제했어요.
2018 Winter Coding는 readmd에서는 삭제됐는데 db.json에는 남아있어서 삭제했어요.
=> 일정이 지난 내용 삭제

README.md, db.json
=> 플리토 안드로이드 개발자 채용

README.md, package-lock.json
인프랩(인프런 www.inflearn.com) 에서 새로운 개발자를 구인하고 있습니다.
해당 공고 (https://www.inflearn.com/recruit201901) 에 대한 글을 업데이트 했습니다.
=> add 인프랩 채용공고

README.md, db.json
트레바리의 url이 변경되어 수정된 url로 수정해서 올립니다
=> [update] 트레바리 url변경

README.md
코멘토 Front-end, Back-end 신입 개발자 채용 url이 유효하지 않아(404 error) 수정하였습니다.
=> [update] 코멘토 FE/BE 채용 url 수정

README.md
안녕하세요 :)
Gap Year를 갖고, 이직을 하는 과정에 고민했던 내용들을(그리고 어떻게 실행했는지) 작성한 블로그 포스팅과 
데이터 사이언스 인터뷰 질문 Github Repo를 추가합니다 :)
=> [update] 이직 후기, 데이터사이언스 인터뷰 질문

README.md, db.json
서류 접수하는 기간이 종료된 것으로 보이는 내용들 삭제했어요.
=> 서류 접수 기간 종료

README.md, db.json
안녕하세요!
2019 네이버 캠퍼스 핵데이 SUMMER 정보가 오픈되어 추가요청 드립니다!
자세한 정보는 아래와 같습니다.
* 지원 기간: ~ 2019.04.04 23:59:59
* 일정
* 2019.04.08 (월) ~ 09 (화): 온라인 코딩테스트 안내 예쩡
* 2019.04.13 (토): 온라인 코딩테스트
* 2019.05.02 (목): 참가자 발표
* 2019.05.16 (목) ~ 17 (금): 핵데이 진행
* 장소: 춘천 NAVER CONNECT ONE
* 16 일 그린팩토리에서 집결 후 단체 이동
* 특전: 우수 참가자는 2019 년 하계인턴십 면접 기회 부여
감사합니다
=> 2019 네이버 캠퍼스 핵데이 SUMMER 정보 추가 요청드립니다!

README.md, db.json
라쿠텐 신입 개발자 채용 공고가 나와 추가 풀리퀘스트 보냅니다
=> rakuten 신입 개발자 채용 추가

README.md, db.json
마감된 Rakuten 신입 개발자 채용 공고 제거했어요.
=> 마감된 Rakuten 신입 개발자 채용 공고 제거

README.md, db.json
=> 지그재그 신입 웹 개발자 채용 마감

README.md
github로 여러 사람들과 다함께 작성한 이력서의 링크를 추가해보았습니다.
https://github.com/JSpiner/RESUME
=> 이력서 레퍼런스 추가

README.md, db.json
신청 기간이 종료된 네이버 신입 공채 설명회를 제거했어요.
=> 신청 기간이 종료된 네이버 신입 공채 설명회 제거

README.md, db.json
[NHN] 2019년 하반기 기술부문 신입사원 공개채용 내용 추가하였습니다!
=> [NHN] 2019년 하반기 기술부문 신입사원 공개채용

README.md, db.json
2019 NAVER 기술 직군 신입사원 공채 추가하였습니다!
=> 2019 NAVER 기술 직군 신입사원 공채 추가하였습니다!

README.md
개정판(4판)이 출간되어서 관린 링크 최신화 했습니다.
=> 개정판 출판에 따른 링크 수정

README.md, db.json
NHN 공개채용 마감시간이 채용공고에 나온 것과 달라 수정합니다.
=> NHN 공개채용 마감시간 수정

README.md, db.json
NAVER CAMPUS HACKDAY 2019 Winter 내용 추가했습니다!
=> NAVER CAMPUS HACKDAY 2019 Winter 추가했습니다!

README-zh_CN.md, README.md, db.json
=> 참가신청이 종료된 해커톤 삭제

README-zh_CN.md, README.md, db.json
2019 Winter Coding - 겨울방학 스타트업 인턴 프로그램 내용 추가하였습니다!
=> 2019 Winter Coding - 겨울방학 스타트업 인턴 프로그램 내용 추가하였습니다!

README-zh_CN.md, README.md
안녕하세요. 
Riiid 채용 페이지 URL이 변경된거로 보여서 수정하여 PR 올립니다.
(Riiid 개발자는 아닙니다 ;;) 
가끔씩 이 저장소 둘러보는데. 좋은 정보들 주셔서 감사합니다!
=> Riiid 채용 페이지 URL 수정

README.md
해설이 올라왔는데 추가가 안돼있어서 추가합니다. 항상 잘 보고 있습니다. 감사합니다!
=> 카카오 신입 공채 테스트 1차 해설 추가

README.md
=> 2020 카카오 신입 공채 테스트 2차 해설 추가

README.md, db.json
=> 라인 스튜디오 채용 연계형 인턴십 추가

README.md, db.json
=> 참가신청이 종료된 인턴 프로그램 삭제

README.md, db.json
=> 웍스모바일 동계 인턴 모집 일정 추가

README.md, db.json
프로그래머스에 올라온 당근마켓 블라인드 채용을 추가합니다~
혹시 해당 채용이 당근마켓 항목쪽에 넣어야한다면 피드백 부탁드립니다!
=> 당근마켓 블라인드 채용 - 웹 개발 챌린지 추가

README.md, db.json
참가신청이 종료된 LINE studio 정규직 채용 연계형 인턴십 삭제했어요.
=> 참가신청이 종료된 인턴십 삭제

README.md, db.json
=> 종료된 당큰마켓 웹 개발 챌린지 삭제

README.md
254 2017 카카오 코드 페스티벌 해설 URL 수정
=> 2017 카카오 코드 페스티벌 해설 URL 수정

README.md, db.json
접수 마감된 모집공고 제거하면서 하위에 있던 링크들도 모집공고와 관련된 내용이라고 생각되서 같이 지웠어요.
=> 접수 마감된 모집공고 제거

README.md
* 2017 대한민국 인재상 
* SW 마에스트로 9기
* BoB 6기 보안컨설팅 트랙
* 에듀캐스트 Unity 강사  
[나동빈님 네이버 블로그](https://blog.naver.com/PostList.nhn?blogId=ndb796)
[나동빈님 티스토리](https://ndb796.tistory.com)
안경잡이 개발자로 활동하시는 나동빈님 포트폴리오 유튜브 강의를 추가해봤습니다.
[초보 개발자를 위한, 개발자 포트폴리오 만드는 방법](https://www.youtube.com/watch?v=hElB_FY33xs&t=8s)
=> 나동빈님의 초보 개발자를 위한, 개발자 포트폴리오 만드는 방법 추가

README.md, db.json
기존의 주소로 들어가면 404 Error가 나와 수정했습니다.
=> 코멘토 채용페이지 URL 수정

README.md, db.json
안녕하세요
**웹 프론트엔드 개발자 인턴**을 채용하게되어 PR드립니다.
현재 잡플래닛에 리뷰가 있는 상황은 아니지만
1. `유의미한 트래픽이 발생하고`
2. `코드리뷰, 배포 자동화 등이 구축`
👉 CI/CD는 이미 도입 중에 있으며 **Github Flow**를 활용한 PR을 적극적으로 활용 중입니다.
3. `코드 품질에 관심이 있는 회사`  
👉 현재 MVP 개발 방식이 우선이지만 특히 프론트엔드 팀에서는 빠른 일정속에 어떻게하면 유의미한 코드를 작성하고 효율적인 구조를 가져갈지에 대해 고민이 많고 노력 중에 있습니다
스타트업이지만 카카오 공동체로 금전적 압박을 걱정하실 근무 환경은 아니며
특히 프론트엔드 개발자로는 인턴 혹은 신입 경력을 쌓는 게 굉장히 쉽지 않은 현 구직 시장에
능력있는 신입 개발자분에게 큰 경험이 될 수 있을거라고 생각합니다
=> Add: Recruit Movill (intern)

README.md, db.json
매스프레소 채용관련 정보 추가하기 위한 PR 입니다.
첫 PR 인데 혹시 규칙 놓친게 있다면 이야기 해주시면 수정 하겠습니다 :)
=> 매스프레소 채용 관련 정보

README.md
- 데브시스터즈 채용사이트 및 전문연구요원/산업기능요원 채용  url
- 데브시스터즈 기술블로그 
- 기업문화를 살펴 볼 수 있는 링크드인 기업 페이지
변경해야할 부분이나, 수정해야 되는 부분이 있다면 편하게 말씀해주세요! :)
=> 데브시스터즈 신입 개발자 / 병특 채용 추가

README.md, db.json
=> 라인플러스 Global Music 서버 개발 인턴 공고 추가

README.md
- 신입 개발자를 위한 기술 면접 모음
- 30개 기업에서 받은 면접 질문 공유
취업 준비를 하면서 가장 많은 도움이 되었던 레포가 여기 였습니다!!
함께 준비한 스터디원 모두 취업에 성공했고:+1:
취업 준비를 하면서 받은 질문과 답변을 다른 신입 지원자들에게 공유하고자 PR을 날립니다.:smile:
감사합니다!!
=> 30개 기업에서 받은 신입 면접 질문&답변 추가

README.md, db.json
=> 네이버웹툰 개발 인턴십 추가

README-en_EN.md, README-zh_CN.md, README.md
산타토익을 소개하는 페이지로 이동하는 링크는 불필요한 정보라고 생각되어 지웠어요.
=> 불필요한 정보 제거

README-en_EN.md, README-zh_CN.md, README.md, db.json
쿠팡 2020 상반기 신입 개발자 공개채용 (Java, Android, iOS) 추가하였습니다!
=> 쿠팡 2020 상반기 신입 개발자 공개채용 (Java, Android, iOS) 추가

README.md, db.json
“번역은 바로 플리 플리 플리토”
글로벌 천만 유저와 함께하는 플리토(Flitto)에서 iOS 개발자를 채용 중입니다.
번역/데이터 회사로 많이들 알고 계시지만
저희는 사람과 사람을 이어주는 번역 플랫폼을 운영하고 있기 때문에
개발에 대한 중요성은 두말할 필요 없이 높습니다. (실제 창업 멤버 3명 중 2명이 개발자입니다.)
**플리토 개발팀은**
- 글로벌 서비스를 함께 만들며 다양한 경험을 하고 있습니다.
- 개발뿐 아니라 기획, 디자인, 마케팅, QA팀들과 밀접하게 협업하며 DEVOPS를 실천하고 있습니다.
- 개발팀 문화는 스스로 만들어 갑니다.
- 각자 맡은 일에 자부심을 가지고 있습니다.
- iOS 개발자로 탄탄한 성장을 원하신다면 플리토와 함께!
많은 지원 부탁드립니다.
=> 플리토(Flitto) iOS 개발자 채용 공고 추가

README.md, db.json
안녕하세요! 준비물까지 챙겨주는 온라인 클래스, 클래스101의 이병철입니다.
저희의 채용 공고를 추가해보았습니다ㅎㅎ
클래스101 개발팀은 높은 비율의 신입/주니어 개발자로 구성되어있으며, 회사와 개인이 같이 성장하기 위해 조직 문화에서 복지, 일하는 방식까지 여러모로 노력을 하고 있습니다.
서비스가 급격히 성장하며 항상 기술적인 도전과제가 넘치며, 경력과 관계없이 도전해볼 수 있는 기회가 주어지기 때문에 개발자로서 빠르게 성장할 수 있는 곳이라고 생각합니다. 올해 들어서, 함께 성장해 나갈 주니어 개발자분들을 더 많이 모시고 있습니다.
멋진 레포를 관리해주셔서 감사합니다!
=> 클래스101 개발자 채용 공고 추가

README.md, db.json
모빌 프론트엔드 개발자 인턴 채용기간이 마감되어 해당 공고를 제거합니다.
=> 접수 마감된 모집 공고 제거

README.md, db.json
=> 종료된 채용 정보 삭제

README-en_EN.md, README-zh_CN.md, README.md, db.json
3/18 부터 접수 시작 예정인 NAVER 2020 CAMPUS HACKDAY Summer 정보 추가하였습니다!
https://recruit.navercorp.com/naver/job/detail/developer?annoId=20003868
=> NAVER 2020 CAMPUS HACKDAY Summer 정보 추가하였습니다!

README-en_EN.md, README-zh_CN.md, README.md
김대희님의 면접 자료 repo 링크가 더이상 유효하지 않아 제거 후 PR 등록하였습니다.
(링크 접속 안되는 것 인지 후, 당사자에게 별도로 확인 완료)
=> 더이상 유효하지 않은 링크 제거

README.md
5.8 기준으로 마감된 공고들을 삭제했습니다.
또한 오늘 나온 nc소프트 인턴 모집 사이트를 추가했습니다.
=> 마감된 채용공고 수정 & nc소프트 인턴 추가 요청

README.md, db.json
안녕하세요. 제가 재직중인 회사에서 프론트, 백엔드 채용을 하는데 공유하고자 합니다. 
프론트는 주니어, 시니어 둘다 열려있고, 백엔드는 기본적으로 시니어분을 모시고자 합니다. 
[잡플래닛 회사소개](https://www.jobplanet.co.kr/companies/325950/landing/프리윌린)
=> 프리윌린 프론트, 백엔드 채용공고

README.md, db.json
온라인 교육 프로그램인 부스트 코스와 혼동하신것 같아 수정합니다.
=> 부스트 캠프 오타 수정

README.md
1. 컴투스 SUMMER 인턴십 -> 마감이 얼마 남지 않았지만 다양한 분야에서 모집하는 좋은 기회라고 생각해서 추천합니다.
2. iPortfolio Android 개발자 -> programmers 구직 사이트에 올라왔지만 회사의 장점, 복리후생 등 개발자를 위하는 모습이 보여서 추천합니다.
=> 컴투스, iPortfolio 채용 공고 추가

README.md, db.json
네이버에서 진행하는 "AI RUSH"라는 AI 프로젝트입니다. AI에 관심있는 junior 개발자 분들에게 추천하고 싶은 프로젝트입니다.
=> 네이버 AI 프로젝트 인턴십 채용공고 추가

README.md, db.json
네이버에서 상시 채용중인 Computer Vision 인턴십 채용공고입니다. 딥러닝 기술에 기반한 컴퓨터비전에 관심있는 주니어 개발자분들에게 추천합니다.
=> 네이버 Computer Vision 인턴십 채용공고 추가

README.md, db.json
상시 채용중인 에이전트소프트 채용공고입니다. 성장중인 기업이고 워라밸이 좋은 기업이라 PR 보냅니다.
=> 에이전트소프트 채용공고 추가

README-zh_CN.md
중국어 버전 README에 마감이 한참 지난 채용공고가 있어서 제거했습니다.
=> CN버전 만기 채용 제거

README.md, db.json
쿠팡에서 어제 신입개발자를 대상으로 채용공고를 올렸습니다.
다양한 복지와 혜택이 눈에 띄는데요, 
여러 사람들이 보고 지원했으면 좋겠어서 추천해봅니다.
=> 쿠페이 채용공고 추가

README.md, db.json
기존에 네이버 clova와 카카오 엔터프라이즈 공고를 db.json까지 수정하여 올립니다.
=> db.json 수정

README.md
샌드박스 풀스택 개발자 채용 공고는 상시모집이지만 유용한 것 같아서 추가하였습니다.
=> 추가적으로 샌드박스 풀스택 개발자 채용 공고 추가를 요청합니다.

db.json
=> db.json 파일에 json array 구분자 오타 수정

README.md, db.json
네이버 비즈니스 플랫폼(NBP) 하계 인턴십 공고를 추가했습니다.
개발 부문, 엔지니어 부문으로 나눠서 진행하고 있고 다양한 분야에서 모집을 진행하는 것 같습니다.
=> 2020 NBP 하계 인턴십 공고 추가

README.md, db.json
=> 쿠페이 공고가 마감되어 삭제요청 올립니다.

README.md, db.json
안녕하세요 @jojoldu 님.
채용 기간이 지난 기업을 삭제했습니다 ~!
=> 기간이 지난 채용 기업 삭제

README.md, db.json
줌인터넷 검색서비스 수시채용모집이 있어 추가합니다
마감 시 삭제 PR도 올리겠습니다 :)
=> 줌인터넷 검색서비스 개발 신입/경력 채용공고 추가

README.md, db.json
안녕하세요. 
데브시스터즈 주니어 개발 자 채용 공고 수정했습니다. : )
검토 부탁드립니다.
감사합니다!
=> 데브시스터즈 개발 주니어 채용 공고 업로드 및 채용사이트 Url 추가하였습니다.

README.md, db.json
토스 3년차 이하 개발자 채용 공고가 올라와 좋은 정보인 것 같아 추가하였습니다.
Frontend, iOS, Android, Server, Full Stack, Data Engineering 등의 지원분야가 있네요.
주니어 개발자를 위해 좋은 리포지토리 만들고 운영해 주셔서 감사합니다!
=> 토스 3년차 이하 개발자 채용 공고 추가

README.md, db.json
=> 줌인터넷 마감공고 삭제

README.md, db.json
안녕하세요.
지나가다가 종료된 공고가 있는데 PR도 없길래 조심스레 PR 날려봅니다.
항상 좋은 정보들 공유해주셔서 감사합니다. 🥰
=> 네이버 웹툰 개발 인턴 마감공고 삭제

README.md, db.json
안녕하세요!
카카오페이지 글로벌 운영 플랫폼 개발팀 채용 담당자입니다.
공고에는 명시되어 있지 않지만 주니어 개발자를 포함한 개발자 분들을 모집하고 있습니다.
뽑히게 될 개발자분을 잘 케어하고 같이 좋은 개발자로 성장하려는 마음을 가지고 이 레파지토리에 PR 드립니다.
감사합니다.
=> 카카오페이지 글로벌 운영 플랫폼 개발자 채용 정보 추가

README.md, db.json
=> 종료된 토스 채용 공고 삭제

README-en_EN.md, README.md, db.json
- **1억 대의 디바이스. 100만 RPM. 하루 10억 건 이상의 이벤트 데이터를 다루는 데이터 기업**
- **AB180**에서 함께 성장할 엔지니어들을 찾고 있습니다.
- 보다 자세한 내용은 https://abit.ly/ab180 에서 확인해주세요!
=> AB180 엔지니어 영입 안내 추가 ლ( ╹ ◡ ╹ ლ)

README.md, db.json
안녕하세요~! 
카카오페이지 백오피스/운영툴 개발자도 모집을 하고 있습니다.
주니어 개발자분들께서 많은 지원해주셨으면 하는 마음에 PR을 올려드립니다. 
카카오페이지 글로벌 운영 플랫폼 개발자 채용도 기간이 변경되어 있어서 함께 수정을 하였습니다. 
감사합니다~!
=> 카카오 페이지 백오피스/운영툴 개발자 공고 추가

README.md, db.json
뱅크샐러드에서 대대적으로 신입 및 인턴 개발자 채용을 시작합니다.
뱅크샐러드는
* 국내 700만 유저가 사용하는 앱으로, 유의미한 트래픽이 발생하고 있습니다.
* 코드리뷰 문화는 물론이고, 코드를 작성하기 전에 "무엇을 어떻게 왜 만들것인지"에 대한 문서인 `테크스펙`을 작성하고 공유하고 리뷰하는 문화로 인해 지식이 빠르게 전파되어 구성원 개개인의 폭발적인 성장이 가능한 곳입니다.
* 또한 [하루에 천 번 배포하는 조직](https://blog.banksalad.com/tech/become-an-organization-that-deploys-1000-times-a-day/)이 되는 것을 목표로 하는 조직으로, 높은 효율의 배포 자동화 및 배포 모니터링 시스템을 구축하고 있습니다.
신입 개발자가 빠르게 성장할 수 있는 좋은 조건들이 갖춰진 뱅크샐러드에 많은 신입 개발자분들이 지원해 주시면 감사하겠습니다.
=> 뱅크샐러드 신입 및 인턴 개발자 채용을 추가합니다.

README.md, db.json
안녕하세요!
카카오페이지 글로벌 운영 플랫폼 개발팀 채용 담당자입니다.
채용이 종료되어 채용 정보 삭제하려고 PR 드립니다.
감사합니다.
=> 카카오페이지 글로벌 운영 플랫폼 개발자 채용 정보 삭제

README.md, db.json
네이버 쇼핑 검색 플랫폼에서 채용 연계형 인턴 모집이 시작되어 추가하였습니다!
=> [Forest] 네이버 쇼핑검색 플랫폼 개발 인턴십(채용 연계형) 추가했습니다!

db.json
item 사이 구분자가 누락되어 있던 것을 수정하였습니다 :D
=> JSON 오타 수정

README.md, db.json
기간 지난 공고들을 삭제하고 스노우 앱 개발자 공고를 추가하였습니다.
=> 수정: 기간 지난 공고 삭제 및 스노우 공고 추가

README.md, db.json
- `### 추천 기업 (수시 & 상시 채용)`에는 commit history를 살펴보니 최신 링크가 상단에 위치해서 위쪽에 추가했습니다. (혹시 문제가 될 경우 comment 부탁드립니다. 🙏 
- 채용 링크와 더불어 토스팀에 대한 오해를 풀어보는 유투브 영상도 함께 추가합니다 🙇
=> docs: add toss team link

README.md, db.json
내일 오전 11시부터 시작되는 NHN 하반기 공개채용 공고 추가했습니다
링크는 공채 시작시간인 11부터 열린다고 합니다!
=> [NHN] 2020 NHN 공개채용 추가

README.md, db.json
안녕하세요!
마감 일자 지난 채용 공고(네이버 웍스모바일/Dev-Matching)가 있는 것 같아서, 삭제해보았습니다~!
감사합니다.
=> 마감 일자 지난 채용 공고 삭제 (네이버 웍스모바일/Dev-Matching)

README.md, db.json
@jojoldu 
이전에 해당 저장소 덕분에 좋은 분을 채용하여 함께 일하고 있습니다:)
신규 채용을 또 하게 되어서 추가 요청 드립니다. 감사합니다.
=> 코멘토 Front-end 채용 공고 추가

README.md, db.json
안녕하세요!
오랜만에 둘러보다 마감된 공고가 있길래 삭제해보았습니다! 😄
블로그와 책으로 많은 도움 받고 있습니다.
항상 감사드려요 🥰
=> 마감된 NHN 공개채용 공고 삭제

README.md, db.json
안녕하세요!
카카오페이지 글로벌 안드로이드 개발자 공고 추가를 요청드립니다~
=> 카카오페이지 글로벌 안드로이드 개발 공고 추가

README.md, db.json
안녕하세요, 열정에 기름붓기 개발팀입니다.
이렇게 좋은 채용 repo가 있는지 몰랐네요 🤤🤤🤤
채용 정보 추가 PR 드립니다.
---
추가로 부끄럽지만
구글에서 잡플래닛에 열정에 기름붓기 검색 시 preview에 3.4점이라 뜨는데,
좋지 않게 퇴사한 팀원 몇분이 악의적으로 점수를 낮춰 3점대로 잠깐 떨어졌었습니다.
이후 해당 팀원들과 좋게 풀어서 4.7점으로 다시 올라간 상태입니다.
=> 열정에 기름붓기 - 크리에이터 클럽 개발자 채용 공고 추가 요청 드립니다.

README.md, db.json
홈쇼핑모아 서비스를 운영하는 버즈니에서 AI 플랫폼 백엔드 엔지니어를 모집합니다. (신입 / 경력)
추가 부탁드려요~
=> 버즈니 AI 플랫폼 / 백엔드 엔지니어 공고 추가

README.md, db.json
열정에 기름붓기 주니어 개발자 채용 마감되어 공고 제거 PR 올립니다.
덕분에 채용 잘 진행했습니다. 감사합니다 :)
=> 열정에 기름붓기 주니어 개발자 채용 마감

README.md, db.json
안녕하세요 헤이조이스의 정민혁이라고 합니다. 주니어 개발자를 위해 헤이조이스를 Self-추천합니다.
헤이조이스는 설립 2년이 된 어린 스타트업입니다. 2020년 5월 첫번째 개발자로 조인하고 7월 주니어 개발자 두 분을 동료로 모시고 함께 협업하고 있습니다.
사업이 성장함에 따라 멋진 동료를 더 모실 수 있게 되었습니다. 헤이조이스는 초기 스타트업의 개발 문화를 만들기 위해 많은 노력을 하고 있고, 그 과정에 대한 글을 공유합니다.
- https://medium.com/heyjoyce/%EC%B4%88%EA%B8%B0-%EC%8A%A4%ED%83%80%ED%8A%B8%EC%97%85%EC%9D%98-%EA%B0%9C%EB%B0%9C-%EB%AC%B8%ED%99%94-%EB%A7%8C%EB%93%A4%EA%B8%B0-e7ad63876419
=> 헤이조이스 채용 공고 추가

README.md, db.json
안녕하세요. 운전자의 데이터를 세상과 연결해 고민 없는 운전을 만들고 있는 모빌리티 스타트업, 퍼즐벤처스 오일나우 서버 개발자 강주희입니다.
저는 주니어 개발자가 성장하기 위해서는 많은 문제를 해결하는 경험이 중요하다고 생각합니다.
지금까지 저는 보통 문제를 빠르게 해결하는 데에 중점을 두고 해결을 해왔는데, 보통 응급처치 수준으로 문제를 해결하게 되는 경우가 빈번했습니다.
시간이 지남에 따라 응급처치는 결국 큰 문제를 가져오게 되고, 악순환의 반복이 되는 경험을 많이 하였습니다.
결국, 처음 문제를 직면하였을 때, 문제를 어떻게 풀어나가는 지가 중요하다는 것을 깨닫고, 이런 방법을 배워나가고자 오일나우에 입사하였습니다.
그런 면에 있어서 오일나우는 한정된 리소스와 시간 내에서 `문제를 효과적으로 해결하기 위해 많은 노력`을 기울이고 있습니다.
스타트업의 특성상 한정된 리소스와 시간 내에서 문제를 효과적으로 고객 관점에서 해결하기 위해서, `허들(Huddle)`과 `OKR`을 적용하고 있습니다.
허들을 통해 우리가 해결하고자 하는 문제를 명확히하고 해결 방법에 대해 팀원이 함께 고민하여 문제 해결 방법을 선정합니다. 
그 후, 선정된 방법으로 개발을 진행한 후, OKR을 통해 명확한 판단 기준을 바탕으로 회고 과정을 거쳐 합리적인 문제해결 문화를 만들어가고 있습니다.
이처럼 스마트하게 문제를 해결해나가는 오일나우에서 함께 빠르게 성장하고 싶은 주니어 개발자를 위해
아직 초기 스타트업이라 잡플래닛에 리뷰는 없지만, `"개인의 성장이 서비스의 성장"`이라는 모토를 가지고 성장하고 있는 `오일나우`를 Self …
=> 오일나우 웹 프론트 신입/경력 공고 추가

README-en_EN.md, README-zh_CN.md, README.md, db.json
안녕하세요 :)
우선 멋진 Repo 만들어주셔서 감사합니다.
저는 [스켈터랩스](https://www.skelterlabs.com/ko/)에 재직중인 Software Engineer 입니다.
얼마 전 회사를 셀프 추천한다는 다른 분의 PR을 보고서 제가 다니고 있는 회사도 추천하고 싶은 곳이라는 생각이 들어 회사에 직접 허락을 구한 뒤 PR을 만들게 되었습니다.
[잡 플래닛 평점](https://www.jobplanet.co.kr/companies/325868/reviews/%EC%8A%A4%EC%BC%88%ED%84%B0%EB%9E%A9%EC%8A%A4)은 4.6으로 PR 평점 기준을 만족합니다.
개인적으로 **개발자로서 성장하기엔 최적인 곳**이라 생각해서 이직이나 취업을 고민 중이신 주니어 엔지니어분들께 추천을 드리고 싶어요.
이건 잡플래닛 기업 리뷰에서 공통적으로 회자되는 이야기기도 합니다.
구글 출신 엔지니어분들이 많고 그렇지 않으신 분들도 모두 역량이 뛰어나셔서 합류하게 되면 어쩔 수 없이 성장하게 되는, 그런 곳이라고 생각해요.
PR 이 merge 되어서 부디 많은 분들이 저희 회사를 찾아주셨으면 좋겠네요.
감사합니다.
Also fixed:
* 내, 외국인도 가리지 않고 채용 중이라 영문 중문 버전의 README 도 함께 수정하였습니다.
=> 스켈터랩스 채용 공고 추가

README.md
=> [삭제]링크만료 parkscom님의 신입 개발자를 위한 이력서 쓰기

README.md, db.json
2021 네이버웹툰 하계인턴십 채용연계형(개발/리서치) 공고 추가합니다.
Repository 항상 잘 보고 있습니다. 감사합니다. :-)
=> 2021 네이버웹툰 하계인턴십 공고 추가

README.md
안녕하세요! 
여기서 많은 도움을 얻어 이직에 성공했습니다. ^^
이런 자리를 만들어 주셔서 감사합니다!!
저도 이직을 하며 배운 내용과 노하우를 다른 분들과 나누고 싶어 글을 적어 보았습니다.
그리고 minieetea 님께서 쓰신 글 너무 좋아 같이 추가 하였습니다. 
감사합니다!!
=> 이직 팁과 이력서 작성 팁

README.md
정원희님의 브런치 글이 블로그로 이전되어, 블로그 글 링크로 대체하였습니다.
=> 정원희님의 개발자 이력서 작성하기 링크 수정

README.md
New resource link under others
=> Added new resources under Others

README.md
안녕하세요 :)
링크 오류가 있어 수정했습니다. ^^;;
추가 해주셔서 감사합니다!!
=> fix link error

README.md, db.json
안녕하세요.
우연히 우아한테크캠프 4기 모집 안내글이 보여서
다른 개발자분들께 도움이 되지 않을까 해서 추가해보았습니다.
README.md, db.json 내용 수정 및 이미지 추가했습니다.
개발자로서 첫 PR인데 제대로 했는지 모르겠네요 ㅠㅠ
감사합니다.
=> [교육 코스] 2021 우아한테크캠프 4기 모집 안내 추가

README.md
=> 마감된 네이버 인턴 공고 삭제, 카카오 신입 공채 2차 해설 추가

README.md, db.json
안녕하세요! 사람인HR에서 IT연구소 신입 개발자 공개 채용을 시작하여 공고 추천합니다!
사람인은 일일 평균 120만 유저가 방문하며 꾸준히 성장하고 있는 회사입니다.
제가 공채를 통해 입사하고 일하면서 IT 프로세스가 잘 되어있다고 생각합니다! 
3개월 OJT가 체계적으로 잘 되어있고, 신입 개발자가 많은 것을 배울 수 있을 것 같아요.
[잡플래닛 평점](https://www.jobplanet.co.kr/companies/74164/landing/%EC%82%AC%EB%9E%8C%EC%9D%B8%EC%97%90%EC%9D%B4%EC%B9%98%EC%95%8C)은 3.0 으로 기준에 살짝 부족하지만, IT부서의 평점은 충분히 훌륭한 것으로 판단됩니다!
아래 기술블로그나 소개 페이지를 함께 첨부합니다! 😄
- [사람인HR IT연구소 기술블로그](https://saramin.github.io/)
- [서비스HR 소개 Notion](https://www.saraminhr.team/)
=> 사람인 IT연구소 개발자 공개채용 공고 추가

README.md
=> 부스트캠프 웹·모바일 6기 추가

README.md, db.json
안녕하세요 :)
회사 정식 명칭이 [모두싸인](https://modusign.co.kr/)이다보니 변경을 제출하게 됐습니다 ㅎㅎ
=> 모두싸인으로 회사 이름 변경

README.md, db.json
마감된지 한달이나 지났는데 아무도 PR을 안날려서요~!
=> 마감된 2021 사람인 IT 연구소 공개채용

README.md, db.json
=> [Deleted] 네이버 SmartEditor 백엔드 개발 채용연계형 인턴 

README.md, db.json
=> 2021 카카오페이 채용연계형 인턴십 공고

README.md
안녕하세요. 동욱님.
제 소개를 하자면, 전 [현재 테크타카(ARGO)] 라는 물류 IT 회사에서 채용을 담당하고 있으며,
현재 오픈카카오톡방과 개발자 커뮤니티에서 활동하는 테크 리크루터로 재직중인 김현준 이라고 합니다.
저희 테크타카의 개발문화는 정말 좋으나 갓 1년 넘은 스타트업인데, 서비스까지 BTB라 채용에 어려움을 겪고 있습니다. 이런 상황에서 기존 플랫폼에선 공고 노출에서 밀릴수 밖에 없는 상황이라 어떻게 하면 채용 브랜딩을 하고 채용을 잘 할 수 있을까 고민하다가 오픈 카카오톡의 장점을 이해한 후 브랜딩 과 채용을 동시에 진행하려고 다수의 오픈 카카오톡방에서 활동중 웹코딩 STUDY방 방에서 정보를 얻어 깃허브에도 채용공고 올리게 되었습니다 공고 올리는 것을 허락해 주신다면 앞으로 저희 기업에 큰 도움이 될것 같습니다. 
내용 한번 확인 부탁드립니다.
감사합니다.
테크타카 채용매니저 김현준 드림
=> 물류 스타트업 테크타카(ARGO) 채용공고

README.md, db.json
Swingvy 신입 개발자 채용 정보 추가하여 PR 생성합니다.
감사합니다.
=> Swingvy junior back-end engineer hiring

README.md, db.json
=> 카카오페이 채용연계형 인턴십 마감

README.md
토스팀 엔지니어 채용이 중복 존재하고 있어서 제거했습니다 :)
=> 토스팀 엔지니어 채용 중복 제거

README.md, db.json
[Deleted] 42 SEOUL, 부스트캠프 모집기간 종료
=> [Deleted] 42 SEOUL, 부스트캠프 모집기간 종료

README.md, db.json
=> [Add] 2022 KAKAO BLIND RECRUITMENT

README.md, db.json
추천 기업 목록의 채용 마감일 지남으로 인한 삭제입니다.
=> [Deleted]추천 기업 채용 마감

README.md, db.json
=> 상시 채용 기업 추가

README.md, db.json
* [잡플래닛 평점](https://www.jobplanet.co.kr/companies/346698/reviews/%EB%A7%98%ED%8E%B8%ED%95%9C%EC%84%B8%EC%83%81) 4.7
=> ADD: 맘편한세상(맘시터) 백엔드 엔지니어 채용공고 추가

README.md, db.json
잡플래닛 평점 3.6점이며,
이전 회사인 테크타카에서 동욱님 블로그에 공고 게재한 후 채용에 큰 효과를 본경험이 있어서 
이번 회사인 자란다에서도 공고 게재 요청 드리게 되었습니다.
동욱님 확인 부탁드립니다. 
(처음엔 PR 하는 법도 몰라서 시간 오래걸렸는데, 두번째하니 정말 쉽네요 :) 
그리고 EO 유튜브 잘 봤고, 감사의 댓글도 남겼습니다! 항상 감사합니다. 동욱님
=> 자란다 채용 공고 게재 요청드립니다!!!

README.md, db.json
=> [Delete] 마감 기한 지난 기업 삭제

README.md, db.json
안녕하세요! [그리팅](https://www.greetinghr.com)을 만들고 있는 [주식회사 두들린](https://www.jobplanet.co.kr/companies/386254/reviews/%EB%91%90%EB%93%A4%EB%A6%B0)의 CTO 서동민입니다.
그리팅 서비스는 채용 관리 B2B SaaS 솔루션으로,
현재 쏘카, 아이디어스, 샌드박스 등 유명 스타트업이 사용하고 있고
런칭 1년만에 Series A 투자 유치를 준비중인 초고속 성장 서비스입니다.
이제 막 서비스를 안정화하고 있는 팀이라 별도로 마련한 기술블로그 같은 것은 없지만(부끄럽습니다 😂),
함께 성장할 팀원을 구하고자 이렇게 PR 올립니다.
감사합니다 :)
=> 그리팅 채용 추가 요청

README.md, db.json
안녕하세요, 동욱 님!
정보를 문서에 효과적으로 활용하여 지식으로 만들 수 있도록 하는 지식 관리 기반 문서 SaaS **Typed**를 만들고 있는 기업,
비즈니스캔버스의 프론트엔드 개발자 양태환입니다.
저희 비즈니스 캔버스는 아직 초기 스타트업이라 잡플래닛 리뷰는 없지만, 2020년 7월 창업 직후, 블루포인트파트너스, 소풍벤처스, 신한캐피탈 국내 최고의 초기 투자사들로부터 빠르게 투자를 받고, 창업 10개월 만인 올해 5월 100억 원의 기업가치를 인정받으며 미래에셋벤처투자, 카카오벤처스 등 굴지의 VC들로부터 투자유치에 성공하였습니다.
센드버드 한국법인 이상희 대표님이 엔젤투자를 통해 경영전략 고문으로 참여해주셨고, 前 카카오 인사총괄 황성현 대표님, 토스 공동창업자 이태양님도 각각 인사와 제품에 도움을 주시고 계십니다.
미국, 영국, 프랑스, 필리핀 등 다양한 국가에서 학업과 커리어를 경험한 글로벌 역량을 갖춘 25명의 팀으로 구성되어 있고, 팀의 역량을 최대한 살려 
경쟁력 있는 B2C, B2B SaaS 를 만들기 위해 노력하고 있습니다.
특히 저희 개발팀은 항상 더 나은 코드, 더 나은 아키텍쳐, 더 나은 사용성을 위해 모두가 몰입하고 고민하는 열의 넘치는 팀원들로 구성되어 있기 때문에, 정말 개발을 좋아하고, 깊은 고민을 할 줄 아는 좋은 개발자분들을 모셔 더 나은 서비스를 만들고 싶어 이렇게 PR 드립니다.
=> 비즈니스캔버스 프론트엔드/백엔드 개발자 채용 공고 추가 요청

db.json
JSON에서 포맷이 깨진 부분이 있어 이부분을 수정하는 PR입니다.
감사합니다.
=> Fix ill-formatted value in db.json

README.md, db.json
안녕하세요! 채널코퍼레이션(채널톡)입니다.
실력있는 주니어분들을 회사에 모시기 위해 저희 회사 소개와 채용공고를 공유합니다 :)
[채널톡의 잡플래닛 평점](https://www.jobplanet.co.kr/companies/95169/landing/%EC%B1%84%EB%84%90%EC%BD%94%ED%8D%BC%EB%A0%88%EC%9D%B4%EC%85%98)은 4.5점입니다.
=> Add channel talk

README.md
안녕하세요. 동욱님!
물류 IT 스타트업 '볼드나인'에서 기획자로 일하고 있는 최성정이라고 합니다.
동욱님이 나오시는 유투브와 작성하신 블로그 글들을 읽으면서 많이 배우고 있었는데, 얼마전 출연하신 유투브 댓글에서 동욱님의 취업정보 repository가 채용 시 도움이 많이 되었다는 글을 보고 이렇게 남기게 되었습니다.
저희 회사는 '이지스토리지'에서 최근 '볼드나인(BOLD9)'으로 사명을 변경하여, 이전 잡플래닛 평점도 4.4로 좋은 평을 가지고 있는 개발문화도 꽤 괜찮은 스타트업입니다.
지금껏 투자 유치없이, 초기 멤버와 지인 추천 채용으로 개발자 채용을 진행해왔으나, 최근 개발자 채용에 어려움을 겪고 있어 이렇게 요청 드리게 되었습니다.
아직 채용 담당 매니저가 없어 CTO님과 개발팀 매니저분들이 채용을 담당하고 있고, 저와 같이 일할 개발자 분들 채용에 저도 힘을 보태고 싶어 이렇게 요청 드립니다.
곧 투자 유치도 진행할 예정이고, 막 성장하고 있는 스타트업이라 저희 채용공고를 올리는 걸 허락해주신다면 큰 도움이 될 것 같습니다.
감사합니다.
최성정 드림.
=> 물류 스타트업 볼드나인(BOLD9) 채용공고

README.md, db.json
안녕하세요,
주식회사 두들린의 CTO 서동민입니다.
지난번 채용 공고를 올린 이후로 훌륭한 개발자분들께서 많이 지원해 주셨고, 
그 중에서 좋은 인연을 함께할 분들도 찾을 수 있었습니다!
좋은 기회 마련해주셔서 감사합니다 :)
이번 PR 에서는 두들린 팀의 변경된 채용 정보를 반영하여 올립니다.
특히 그리팅 서비스의 채용 페이지 기능을 통해 만들어진 회사 소개 페이지 또한 첨부합니다!
감사합니다 :)
=> 두들린 채용정보 변경

README.md
안녕하세요 동욱님! 
한국 웹툰과 웹소설을 500만 해외 독자들에게 서비스 하고 있는 Tappytoon의 데이터 엔지니어 [천지은](https://www.linkedin.com/in/g471000/)이라고 합니다. 항상 좋은 정보와 지식 공유 감사드립니다.
Tappytoon은 2018년에 현 CTO님 영입 이후, 새롭고 효율적인 개발팀 문화를 만들어가고 있습니다. 최근에는 네이버 웹툰의 시리즈B 투자를 유치했습니다. 저는 1년전 이 회사에 조인하게 되었고, 팀원분들과 함께 좋은 개발문화를 만들어가고 있다고 생각합니다. Job Planet에 3.2로 나와있는데요, 추측으로는 퇴사하신 직원분들의 일침이 담겨있는것 같습니다. 최근에 조인해서 많은 프로젝트를 진행하고, 협업을 해본 저의 생각은, 배울수 있는 문화 그리고 팀원들의 삶을 존중하는 문화를 만들어가는 회사라고 느꼈습니다. 또, 성장 가능성도 높고 안정적으로 수익을 내고 있기 때문에 충분히 IPO의 가능성도 바라볼 수 있다고 생각합니다. 저희 개발팀은 코드 퀄리티에 정말 많이 신경을 씁니다. 아무리 해야할일이 많아도, 개발자 한명한명의 성장을 위해 힘쓰고 있으며 야근문화를 지양합니다.
태피툰 개발자 채용 정보를 게시해주실 수 있으신지요? 다시한번 감사드립니다.
=> update tappytoon's software enginner recruitment info

README.md, db.json
안녕하세요!
오일나우 개발자 김태성입니다.
현재 채용중인 포지션 변경이 있어 그 내용을 수정하고,
신입분들이 취업에 도움될 수 있도록 포트폴리오 작성에 관한 팁을 글로 작성하여 공유드립니다!
감사합니다.
=> 오일나우 채용 공고 수정 및 포트폴리오 관련 블로그 글 추가

README.md, db.json
안녕하세요.
2022년 상반기 LINE 공개채용 공고가 올라와서 추가합니다.
=> 2022 상반기 신입 LINER 공개 채용 추가

README.md
* github 으로 유입이 괘 많이 비중을 차지 하고 있어요! (도움 많이 되고 있습니다 👍)
=> MOD: 맘편하세상 채용 링크수정 및 기술블로그 링크 추가

README.md, db.json
안녕하세요. 
넥슨 코리아 시니어 아키텍트 심승용입니다.
유투브 항상 재미있게 보고 있습니다.
이번에 팀내 주니어 개발자 TO가 있어 MR를 작성하게 되었습니다.
기술적인 흥미가 높은 주니어를 찾고 있는데 도움을 받을 수 있으면 좋겠습니다.
감사합니다.
=> 넥슨 코리아 개인화개발팀 백엔드 개발(C#) 채용

README.md
링크된 내용 중에 잘못된 링크가 있다는 이슈(#402)가 있어서 수정했어요.
이전에 작성되었던 링크되어있던 내용이 정확히 어떤 내용인지 몰라서 삭제하려다가
wantedlab의 brunch에 올라와 있는 글들을 확인했고 맥락상 같은 내용이라고 생각되면서 내용도 나쁘진 않은 거 같아서 URL만 수정하는 방향으로 커밋해서 PR했어요~
=> fix #402 잘못된 링크 수정

README.md, db.json
안녕하세요, 커먼컴퓨터 Software Engineer 장래영 입니다.
저희 회사 채용공고 내용을 추가한 PR을 보냅니다.
- [홈페이지](https://comcom.ai/)
- [채용 공고](https://link.ainize.ai/3HZkIZN)
- [잡플래닛 링크](https://www.jobplanet.co.kr/companies/374263/reviews/%EC%BB%A4%EB%A8%BC%EC%BB%B4%ED%93%A8%ED%84%B0)
감사합니다!
=> 커먼컴퓨터 채용 공고 추가

README.md, data/db.json
안녕하세요. :) 
버즈빌 채용 플랫폼이 워커블(workable)에서 그리팅(greeting)으로 변경되면서 링크 수정했습니다. 감사합니다.
=> 버즈빌 채용 링크 수정

README.md, data/db.json
안녕하세요. AB180 정주홍입니다.
AB180 백엔드 팀이 백엔드 그룹으로 바뀌고 여러 팀으로 나뉘어졌습니다.
이에 따라 변경된 JD를 반영하고자 합니다.
좋은 repo를 운영해주셔서 항상 감사합니다!
=> AB180 백엔드 그룹 팀별 JD로 업데이트

README.md, data/db.json
안녕하세요! [비사이드](https://bsidekr.notion.site/67e415e8f6094175a4dd5d86cdb0d265)를 만들고 있는 CTO 소재우입니다.
비사이드는 주식 의결권 위임 서비스로,
출시 한달여 만에 3개의 상장사를 대상으로 1,200억원의 주식을 양도받고, 이중 에스엠 주주총회에서 완승은 거두었습니다.
이제 3달째 되는 신규 서비스지만,
좋은 성과를 거두어 Series A 투자 유치 준비중에 있으며,
같이 성장할 팀원을 구하고자 이렇게 PR 올립니다.
현재 별도의 기술 블로그는 없지만,
개발 문화는 이전에 제가 창업하고 exit한 블랙루비스튜디오라는 회사의 개발 문화를 그대로 이어가고 있습니다. (블랙루비스튜디오는 현재 잡플래닛 기준 4.0으로, 제가 나온 이후 아쉽게도 떨어졌습니다 😢)
채용이 된다면, 새로 오신분들과 함께 "주식 위임 서비스"에서 "거버넌스 개선 플랫폼"으로 서비스를 한층 더 성장 시키고자 합니다.
감사합니다 :)
=> 비사이드코리아 채용공고 추가 요청

README.md
안녕하세요, 태피툰의 데이터 엔지니어 천지은(Genie) 입니다.
항상 유투브 채널에서 그리고 대외적으로 공유해주시는 리소스들과 긍정적 영향 감사드립니다.
채용 정보들과 링크가 업데이트 되어서 수정했습니다.
감사드립니다 :)
=> update tappytoon's recruitment links

README.md, data/db.json
당근마켓 Rnd 엔지니어 인턴 클릭시 찾을 수 없는 페이지 발생으로 삭제합니다.
=> 찾을 수 없는 공고 삭제

README.md
안녕하세요! 채널코퍼레이션(채널톡)의 송동욱(Mong)입니다.
최근 고객사가 증가하여 채널톡 설명을 바꾸고, 채널톡 블로그 url을 추가하였습니다
감사합니다 :)
=> 채널톡 설명 수정, 블로그 주소 추가

README.md
안녕하세요.
넥슨 코리아 시니어 아키텍트 심승용입니다.
관련 링크를 업데이트 하였습니다.
감사합니다.
=> 넥슨 코리아 개인화개발팀 백엔드 개발(C#) 채용 업데이트

README.md, data/db.json
- 네이버 신입 공채 정보를 추가하였습니다.
- 기간이 지난 공채 정보를 삭제하였습니다.
늘 감사드립니다!
=> 네이버 신입 공채 추가

README.md, data/db.json
README.md, db.json 둘 다 수정 완료했습니다.
=> 넥스트유니콘 채용 공고 추가

README.md, data/db.json
안녕하세요, 큐엠아이티 Backend Engineer 김명관 입니다.
자사 채용공고 내용을 추가한 PR 요청합니다.
[홈페이지](https://plco.pro/)
[채용 공고](https://qmit-careers.oopy.io/)
[잡플래닛 링크](https://www.jobplanet.co.kr/companies/342451/reviews/%ED%81%90%EC%97%A0%EC%95%84%EC%9D%B4%ED%8B%B0)
감사합니다!
=> 큐엠아이티 채용공고 추가

README.md
- 당근페이 서버개발자 인턴
- 야놀자 클라우드 엔지니어 인턴
=> 존재하지 않는 채용 링크 삭제

README.md, data/db.json
매번 채용공고가 수정될 때마다 풀리퀘 확인 요청드리는게 죄송해서,
오일나우 채용공고 게시판 링크로 수정했습니다!
감사합니다.
=> 오일나우 채용 공고 수정

README.md
안녕하세요,
비사이드코리아 CTO 소재우입니다.
이전에 채용공고를 등록 했었는데 채용기간이 종료되어 [PR](https://github.com/jojoldu/junior-recruit-scheduler/commit/f78b3c35de34a728f3440726f3545fb9b1c1c7da)에서 공고가 삭제되었습니다.
올해 방식을 상시 채용으로 바꾸어서 다시 PR을 요청 드립니다.
감사합니다.
=> 비사이드 채용공고 추가

README-en_EN.md, README.md
- 네이버 면접시 듣게 되는 41가지 질문
- 카카오 면접 시 듣게 되는 70가지 질문
- 애플 면접에서 듣게 되는 33가지 질문
위 내용의 링크가 변경되어 기존 링크로 아티클에 접근할 수 없었고 이를 수정하였습니다.
=> 유효하지 않은 링크 수정(bloter.net)

README.md, data/db.json
커먼컴퓨터 채용 페이지 주소 및 인턴 후기 링크를 업데이트 하였습니다.
=> 커먼컴퓨터 채용 페이지 및 인턴 후기 업데이트

README.md, data/db.json
안녕하세요.
크레비스파트너스 개발팀 팀장 한재준입니다.
함께 재밌게 성장할 동료를 구하기 위해 PR 요청드립니다.
감사합니다.
브릭투웍스(Brictoworks: Brick to works)는 임팩트 벤처를 육성하고 투자하는 크레비스의 기술사업 전문 그룹입니다.
대표 제품인 도너스(Donus)는 2017년에 SaaS(Software-as-a-Service)로 출시되어 2년 만에 비영리 CRM 시장의 리더가 되었으며 매년 2배씩 빠른 속도로 성장하고 있습니다. 도너스의 관리 규모는 2020년 상반기 기준 회원 수 110만명 이상, 기부금 2조원 이상입니다.
- 크레비스파트너스 홈페이지([링크](https://www.crevisse.com/))
- 채용공고([링크](https://www.crevisse.com/careers/?q=YToxOntzOjEyOiJrZXl3b3JkX3R5cGUiO3M6MzoiYWxsIjt9&bmode=view&idx=13283180&t=board))
- 잡플래닛([링크](https://www.jobplanet.co.kr/companies/52356/reviews/%ED%81%AC%EB%A0%88%EB%B9%84%EC%8A%A4%ED%8C%8C%ED%8A%B8%EB%84%88%EC%8A%A4), 2022-11-01 기준 3.8점)
```
- 코드리뷰 : 모든 코드는 배포 전 코드리뷰를 거치도록 하고 있습니다.
여러 개발자들이 더 나은 설계와 구현을 위한 방법을 논의하고 반영합니다.
- DevOps : 테스트 및 배포 과정을 최대한 자동화하는 것을 목표로 합니다.
Azure DevOps를 …
```
=> 크레비스파트너스 채용 공고 추가

README.md, data/db.json
안녕하세요. 메이아이 CPO 김찬규입니다.
함께 탁월한 제품을 만들어나가며 성장할 동료를 구하고 있습니다.
이에 PR 요청드리게 되었습니다 :)
**메이아이**는 인공지능 영상처리 기술에 기반하여, 오프라인 공간의 방문객 데이터를 분석하는 플랫폼을 서비스하고 있는 B2B SaaS 스타트업입니다.
최근에는 **observability**라는 키워드에 집중하고 있습니다.
Observability란 "시스템의 내부 상태를, 시스템이 생성하는 데이터를 통해 파악할 수 있는 정도"를 뜻하는데요. 최근 시스템의 복잡성이 점점 높아지면서, 기존 방식의 모니터링으로는 해결할 수 없는 비효율들을 해결하기 위해 제시되는 개념입니다.
이러한 observability 개념을 오프라인 공간에 접목하여, 오프라인 공간을 데이터를 통해 파악하고 최적화할 수 있는 플랫폼을 구현하고자 합니다.
채용 공고의 링크는 다음과 같습니다: [링크](https://recruit-may-i.oopy.io/backend-developer)
감사합니다!
=> 메이아이 백엔드 개발자 채용 추가
